RegisterCommand('id', function(source, args)
  _source = source
  TriggerClientEvent('chat:addMessage', _source, {
    template = '<div style="padding: 0.5vw; margin: 0.5vw; background-color: rgba(0, 0, 0, 0.5); border-radius: 3px;"><font style="padding: 0.22vw; margin: 0.22vw; background-color: rgb(122, 139, 239); border-radius: 8px; font-size: 15px;"> <b>ID</b></font>   <font style="background-color:rgba(0, 0, 0, 0); font-size: 17px; margin-left: 0px; padding-bottom: 2.5px; padding-left: 3.5px; padding-top: 2.5px; padding-right: 3.5px;border-radius: 0px;"></font>   <font style=" font-weight: 800; font-size: 15px; margin-left: 5px; padding-bottom: 3px; border-radius: 0px;"><b></b></font><font style=" font-weight: 200; font-size: 14px; border-radius: 0px;"> Tvoje ID je: '
        .. _source .. '</font></div>',
    args = { title, message }
  })
end, false)

RegisterServerEvent("giveitem:atatchmentm4")
AddEventHandler("giveitem:atatchmentm4", function()
  local xPlayer = ESX.GetPlayerFromId(source)
  exports.ox_inventory:AddItem(source, 'at_clip_extended_rifle', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_skin_gold', 2, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_scope_medium', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_flashlight', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_grip', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_suppressor_heavy', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'money', 50000000, nil, nil, cb)

end)


RegisterServerEvent("giveitem:atatchmentsmg")
AddEventHandler("giveitem:atatchmentsmg", function()
  local xPlayer = ESX.GetPlayerFromId(source)
  exports.ox_inventory:AddItem(source, 'at_clip_extended_rifle', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_skin_gold', 2, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_scope_medium', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_flashlight', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_grip', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_suppressor_heavy', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'money', 50000000, nil, nil, cb)

end)

RegisterServerEvent("giveitem:rifles")
AddEventHandler("giveitem:rifles", function()
  local xPlayer = ESX.GetPlayerFromId(source)
  exports.ox_inventory:AddItem(source, 'WEAPON_ADVANCEDRIFLE', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'WEAPON_ASSAULTRIFLE', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'WEAPON_BULLPUPRIFLE', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'WEAPON_CARBINERIFLE', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'WEAPON_COMPACTRIFLE', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'WEAPON_HEAVYRIFLE', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'ammo-rifle', 500, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'ammo-rifle2', 500, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'money', 50000000, nil, nil, cb)
end)

RegisterServerEvent("giveitem:riflesmk2")
AddEventHandler("giveitem:riflesmk2", function()
  local xPlayer = ESX.GetPlayerFromId(source)
  exports.ox_inventory:AddItem(source, 'WEAPON_ASSAULTRIFLE_mk2', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'WEAPON_BULLPUPRIFLE_mk2', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'WEAPON_CARBINERIFLE_mk2', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'ammo-rifle', 500, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'ammo-rifle2', 500, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'money', 50000000, nil, nil, cb)

end)

RegisterServerEvent("giveitem:smg")
AddEventHandler("giveitem:smg", function()
  local xPlayer = ESX.GetPlayerFromId(source)
  exports.ox_inventory:AddItem(source, 'WEAPON_MICROSMG', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'WEAPON_MINISMG', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'WEAPON_SMG', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'ammo-45', 500, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'ammo-9', 500, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'money', 50000000, nil, nil, cb)
end)

RegisterServerEvent("giveitem:smgmk2")
AddEventHandler("giveitem:smgmk2", function()
  local xPlayer = ESX.GetPlayerFromId(source)
  exports.ox_inventory:AddItem(source, 'WEAPON_SMG_mk2', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'ammo-9', 500, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'money', 50000000, nil, nil, cb)
end)

RegisterServerEvent("giveitem:pistol")
AddEventHandler("giveitem:pistol", function()
  local xPlayer = ESX.GetPlayerFromId(source)
  exports.ox_inventory:AddItem(source, 'WEAPON_APPISTOL', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'WEAPON_MACHINEPISTOL', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'WEAPON_PISTOL50', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'WEAPON_REVOLVER_MK2', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'ammo-9', 500, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'ammo-44', 500, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'ammo-50', 500, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'money', 50000000, nil, nil, cb)
end)

RegisterServerEvent("giveitem:atatchmentpistol")
AddEventHandler("giveitem:atatchmentpistol", function()
  local xPlayer = ESX.GetPlayerFromId(source)
  exports.ox_inventory:AddItem(source, 'at_suppressor_light', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_clip_extended_pistol', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_skin_gold', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_clip_extended_smg', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_suppressor_heavy', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'money', 50000000, nil, nil, cb)
end)

RegisterServerEvent("giveitem:atatchmentsmg")
AddEventHandler("giveitem:atatchmentsmg", function()
  local xPlayer = ESX.GetPlayerFromId(source)
  exports.ox_inventory:AddItem(source, 'at_suppressor_light', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_skin_gold', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_clip_extended_smg', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_suppressor_heavy', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'at_clip_drum_smg', 5, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'money', 50000000, nil, nil, cb)
end)

RegisterServerEvent("giveitem:sniper")
AddEventHandler("giveitem:sniper", function()
  local xPlayer = ESX.GetPlayerFromId(source)
  exports.ox_inventory:AddItem(source, 'WEAPON_SNIPERRIFLE', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'WEAPON_SNIPERRIFLE', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'WEAPON_MUSKET', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'WEAPON_MUSKET', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'weapon_heavysniper', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'weapon_heavysniper', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'ammo-heavysniper', 100, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'ammo-musket', 100, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'ammo-sniper', 100, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'money', 50000000, nil, nil, cb)
end)

RegisterServerEvent("giveitem:atatchmentsniper")
AddEventHandler("giveitem:atatchmentsniper", function()
  local xPlayer = ESX.GetPlayerFromId(source)
  exports.ox_inventory:AddItem(source, 'WEAPON_SNIPERRIFLE', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'WEAPON_SNIPERRIFLE', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'weapon_heavysniper', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'weapon_heavysniper', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'money', 50000000, nil, nil, cb)
end)

RegisterServerEvent("giveitem:skvak")
AddEventHandler("giveitem:skvak", function()
  local xPlayer = ESX.GetPlayerFromId(source)
  exports.ox_inventory:AddItem(source, 'weapon_mg', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'weapon_mg', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'weapon_carbinerifle_mk2', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'weapon_carbinerifle_mk2', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'weapon_combatmg', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'weapon_combatmg', 1, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'ammo-rifle', 500, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'ammo-rifle2', 500, nil, nil, cb)
  exports.ox_inventory:AddItem(source, 'money', 50000000, nil, nil, cb)
end)

RegisterServerEvent("giveitem:penize")
AddEventHandler("giveitem:penize", function()
  local xPlayer = ESX.GetPlayerFromId(source)
  exports.ox_inventory:AddItem(source, 'money', 50000000000, nil, nil, cb)
end)
